// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4OIzA4RwsmXdh0GK6x6LJnRHuz5VCsn8',
    appId: '1:621062689966:web:82876b6c6234fa2120893f',
    messagingSenderId: '621062689966',
    projectId: 'sales-tracker-app-60e24',
    authDomain: 'sales-tracker-app-60e24.firebaseapp.com',
    storageBucket: 'sales-tracker-app-60e24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Ye9ekyodl7mx_gTP0mvd7DQLQIStDhs',
    appId: '1:621062689966:android:2c654809e2ed426a20893f',
    messagingSenderId: '621062689966',
    projectId: 'sales-tracker-app-60e24',
    storageBucket: 'sales-tracker-app-60e24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGl-FI7D8tR8zfQEz-4mgcV_oS8KF-Ifo',
    appId: '1:621062689966:ios:5a3ee3d765b14af220893f',
    messagingSenderId: '621062689966',
    projectId: 'sales-tracker-app-60e24',
    storageBucket: 'sales-tracker-app-60e24.firebasestorage.app',
    iosBundleId: 'com.example.salesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGl-FI7D8tR8zfQEz-4mgcV_oS8KF-Ifo',
    appId: '1:621062689966:ios:5a3ee3d765b14af220893f',
    messagingSenderId: '621062689966',
    projectId: 'sales-tracker-app-60e24',
    storageBucket: 'sales-tracker-app-60e24.firebasestorage.app',
    iosBundleId: 'com.example.salesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4OIzA4RwsmXdh0GK6x6LJnRHuz5VCsn8',
    appId: '1:621062689966:web:e5fad801107b3dc320893f',
    messagingSenderId: '621062689966',
    projectId: 'sales-tracker-app-60e24',
    authDomain: 'sales-tracker-app-60e24.firebaseapp.com',
    storageBucket: 'sales-tracker-app-60e24.firebasestorage.app',
  );
}
